FROM python:3.9

COPY ./trunk/requirements.txt /trunk/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /trunk/requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]