version: "3.9"

services:
  kafka:
    image: bitnami/kafka:3.5.1
    container_name: kafka
    user: root
    ports:
      - "9094:9094"
    volumes:
      - ${DOCKER_DIR}/kafka:/bitnami/kafka
    restart: always
    networks:
      - kafka_net
    environment:
      - TZ=Asia/Shanghai
      - KAFKA_CFG_NODE_ID=1
      # 设置broker最大内存，和初始内存
      - KAFKA_HEAP_OPTS=-Xmx256M -Xms128M
      # 允许使用PLAINTEXT监听器，默认false，不建议在生产环境使用
      - ALLOW_PLAINTEXT_LISTENER=yes
      # 允许使用kraft，即Kafka替代Zookeeper
      - KAFKA_ENABLE_KRAFT=yes
      # 使用Kafka时的集群id，集群内的Kafka都要用这个id做初始化，生成一个UUID即可
      - KAFKA_KRAFT_CLUSTER_ID=relM2oIFQkiUFvgCEcqRWb
      # kafka角色，做broker，也要做controller
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # 指定供外部使用的控制类请求信息
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      # 定义kafka服务端socket监听端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      # 定义安全协议
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      # 集群地址
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      # 不允许自动创建主题
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      # 定义外网访问地址（宿主机ip地址和端口）
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092,EXTERNAL://localhost:9094

  kafka-console:
    image: redpandadata/console:latest
    container_name: kafka-console
    ports:
      - "9099:8080"
    restart: always
    networks:
      - kafka_net
    environment:
      KAFKA_BROKERS: "kafka:9092"

networks:
  kafka_net:
    name: service_net
    external: true
